// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#pragma once

#include "frc/commands/Subsystem.h"
#include "frc/DigitalInput.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "ctre/Phoenix.h"
#include "frc/Servo.h"
#include "frc/Solenoid.h"
#include "rev/CANSparkMax.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 *
 *
 * @author ExampleAuthor
 */
class Climber: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
std::shared_ptr<rev::CANSparkMax> climberMotor;
std::shared_ptr<frc::Servo> rachetServo;
std::shared_ptr<frc::Solenoid> climberSolenoid;
std::shared_ptr<WPI_VictorSPX> shimmyMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<frc::DigitalInput> rachetDetection;
	double extendStart = 0;
	double retractCnt = 0;
	bool isExtended = false;
	bool isClimbing = false;
public:
Climber();
	void InitDefaultCommand() override;
	void Periodic() override;

	bool lock();
	bool unlock();
	void setClimberPosition(double position);
	void shiftToExtendMode();
	void shiftToWinchMode();
	void setClimberPower(double power);
	void setShimmyMotor(double power);
	//Call this 50 times a second until return true, upon true the climbing arm will be full extended
	bool extend();
	bool retract();

	int cnt = 0;
	double pullupPos = 0;
	int unlockCase = 0;
	int extendCase = 0;
	int retractCase = 0;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS


};

