// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#pragma once

#include "frc/commands/Subsystem.h"
#include <frc/util/color.h>
#include "rev/ColorSensorV3.h"
#include "rev/ColorMatch.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "frc/Solenoid.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

static constexpr auto i2cPort = frc::I2C::Port::kOnboard;

/**
 *
 *
 * @author ExampleAuthor
 */
class ControlPanel: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
std::shared_ptr<frc::Solenoid> wheelManipulator;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
ControlPanel();
	void InitDefaultCommand() override;
	void Periodic() override;
	void deployWheelManipulator();
	void retractWheelManipulator();

	static constexpr frc::Color m_BlueTarget = frc::Color(0.143, 0.427, 0.429);
	static constexpr frc::Color m_GreenTarget = frc::Color(0.197, 0.561, 0.240);
	static constexpr frc::Color m_RedTarget = frc::Color(0.561, 0.232, 0.114);
	static constexpr frc::Color m_YellowTarget = frc::Color(0.361, 0.524, 0.113);

	rev::ColorSensorV3 m_ColourSensor{i2cPort};
	rev::ColorMatch m_ColourMatcher;
	double m_Confidence;
	frc::Color m_Colour;
	std::string m_ColourString;
	uint32_t m_Proximity;
	double m_Blue;
	double m_Red;
	double m_Green;
	double m_IR;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS


};

