// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#pragma once

#include "frc/commands/Subsystem.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "ctre/phoenix.h"
#include "frc/Solenoid.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 *
 *
 * @author ExampleAuthor
 */
class Shooter: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
std::shared_ptr<WPI_TalonSRX> shooterMotor1;
std::shared_ptr<WPI_TalonSRX> shooterMotor2;
std::shared_ptr<WPI_TalonSRX> shooterMotor3;
std::shared_ptr<WPI_TalonSRX> shooterMotor4;
std::shared_ptr<WPI_TalonSRX> hoodMotor;
std::shared_ptr<frc::Solenoid> hoodLock;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
Shooter();
	void InitDefaultCommand() override;
	void Periodic() override;

	void SetShooterSpeed(double speed);
	void stopShooter();

	//void hoodLow();
	//void hoodMedium();
	//void hoodHigh();
	double readEncoderPos();
	void lockHood();
	void releaseHood();
	bool goToHoodPos(double target);
	bool shoot();

	void configHoodTarget(double target);
	void configAimTarget(double target);
	void configShootVel(double target);
	
	double getHoodTarget();
	double getAimTarget();
	double getTargetShootVel();
	double getShooterVel();
	double getVelError();

	double findHoodError();

	int count = 0;
	int delayCount = 0;
	int shootState = 0;
	int ballCounter = 0;
	int shootDelay = 0;

	double hoodTargetPos = 0;
	double autoAimTarget = 0;
	double shootTargetVel = 0;

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS


};

