// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Commands/ConfigureShot.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ConfigureShot::ConfigureShot(int shotSetting): frc::Command() {
m_shotSetting = shotSetting;
    // Use Requires() here to declare subsystem dependencies
    // eg. Requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void ConfigureShot::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void ConfigureShot::Execute() {
    switch (m_shotSetting){
        case 2: //long shot
            Robot::shooter->configAimTarget(0);
            Robot::shooter->configShootVel(1000);
            Robot::shooter->configHoodTarget(1000);
        break;
        case 3: //medium shot
            Robot::shooter->configAimTarget(0);
            Robot::shooter->configShootVel(1000);
            Robot::shooter->configHoodTarget(750);
        break;
        case 4: //close shot
            Robot::shooter->configAimTarget(0);
            Robot::shooter->configShootVel(1000);
            Robot::shooter->configHoodTarget(0);
        break;    
    }
}

// Make this return true when this Command no longer needs to run execute()
bool ConfigureShot::IsFinished() {
    return true;
}

// Called once after isFinished returns true
void ConfigureShot::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ConfigureShot::Interrupted() {

}
