// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Commands/IntakeDeploy.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

IntakeDeploy::IntakeDeploy(): frc::Command() {
    // Use Requires() here to declare subsystem dependencies
    // eg. Requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::intakes.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void IntakeDeploy::Initialize() {
    Robot::intakes->deployIntakes();
}

// Called repeatedly when this Command is scheduled to run
void IntakeDeploy::Execute() {
    if (Robot::oi->getOperatorGamepad()->GetPOV() == 90) {
        Robot::intakes->setIntakeSpeed(0,0.7,0.7);
    } else if (Robot::oi->getOperatorGamepad()->GetPOV() == 180) {
        Robot::intakes->setIntakeSpeed(0.7,0.7,0.7);
    }  else if (Robot::oi->getOperatorGamepad()->GetPOV() == 270) {
        Robot::intakes->setIntakeSpeed(0.7,0,0.7);
    }
    else {
        Robot::intakes->stopIntakes();
    }
}

// Make this return true when this Command no longer needs to run execute()
bool IntakeDeploy::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void IntakeDeploy::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void IntakeDeploy::Interrupted() {

}
