// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Commands/LongShot.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

LongShot::LongShot(): frc::Command() {
    // Use Requires() here to declare subsystem dependencies
    // eg. Requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void LongShot::Initialize() {
    Robot::shooter->releaseHood();
}

// Called repeatedly when this Command is scheduled to run
void LongShot::Execute() {
    done = Robot::shooter->goToHoodPos(1500); //change this constant for high hood position
}

// Make this return true when this Command no longer needs to run execute()
bool LongShot::IsFinished() {
    return done;
}

// Called once after isFinished returns true
void LongShot::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void LongShot::Interrupted() {

}
