// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Subsystems/Intakes.h"
#include <frc/SmartDashboard/SmartDashboard.h>

const double INTAKESPEED = 0.70;
const double MAGSPEED = 1;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Intakes::Intakes() : frc::Subsystem("Intakes") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
sideRoller.reset(new rev::CANSparkMax(9, rev::CANSparkMax::MotorType::kBrushless));


middleRoller.reset(new rev::CANSparkMax(10, rev::CANSparkMax::MotorType::kBrushless));


magazine.reset(new rev::CANSparkMax(11, rev::CANSparkMax::MotorType::kBrushless));


indexer1.reset(new frc::DigitalInput(0));
AddChild("indexer1", indexer1);

indexer2.reset(new frc::DigitalInput(1));
AddChild("indexer2", indexer2);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    double intakeSpeed = 0.3;
	double magSpeed = 0.4;

    frc::SmartDashboard::PutNumber("Intake Speed",intakeSpeed);
    frc::SmartDashboard::PutNumber("Magazine Speed",magSpeed);
}

void Intakes::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void Intakes::Periodic() {
    // Put code here to be run every loop
    intakeSpeed = frc::SmartDashboard::GetNumber("Intake Speed",0.5);
    magSpeed = frc::SmartDashboard::GetNumber("Magazine Speed",0.5);
    frc::SmartDashboard::PutBoolean("Index1",indexer1->Get());
    //index();
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


// Put methods for controlling this subsystem
// here. Call these from Commands.

bool Intakes::index(){
    if(idxState > 0)
        idxcnt++;
    frc::SmartDashboard::PutNumber("Indexer State",idxState);
    frc::SmartDashboard::PutNumber("Indexer Timer",idxcnt);
    switch(idxState){
        case 0:
            if(!indexer1->Get())
                idxState = 1;
            break;
        case 1:
            magazine->Set(-0.4);
            prevDetect = indexer2->Get();
            idxcnt = 0;
            if(!prevDetect)
                idxState = 1;
            else
                idxState = 2;
            break;
        case 2:
            //Wait until indexer1 finds a gap
            prevDetect = indexer2->Get();
            if((prevDetect)){
                idxState = 3;
                idxcnt = 0;
            }
            break;
        case 3:
            prevDetect = indexer2->Get();
            if((!prevDetect)){
                //We have the ball in the right place, stop the motor
                magazine->Set(0);
                idxState = 0;
                return true;
            }
            break;
    }
    return false;
}

void Intakes::spinIntakes(){
    sideRoller->Set(INTAKESPEED);
    middleRoller->Set(INTAKESPEED);
}

void Intakes::stopIntakes(){
    sideRoller->Set(0);
    middleRoller->Set(0);
}

void Intakes::spitoutIntakes(){
    sideRoller->Set(-INTAKESPEED);
    middleRoller->Set(-INTAKESPEED);
}

void Intakes::spinMag(){
    //magazine->Set(MAGSPEED);
}

void Intakes::stopMag(){
    magazine->Set(0);
}

void Intakes::spitoutMag(){
    //magazine->Set(-MAGSPEED);
}
