// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Subsystems/Shooter.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    //Shooter PID values
    const double shooter_P = 0.5;
    const double shooter_I = 0;
    const double shooter_D = 0;

Shooter::Shooter() : frc::Subsystem("Shooter") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
shooterMotor1.reset(new WPI_TalonSRX(9));


shooterMotor2.reset(new WPI_TalonSRX(10));


shooterMotor3.reset(new WPI_TalonSRX(11));


shooterMotor4.reset(new WPI_TalonSRX(12));


hoodSolenoid.reset(new frc::Solenoid(0, 2));
AddChild("hoodSolenoid", hoodSolenoid);

hoodMidSolenoid.reset(new frc::Solenoid(0, 3));
AddChild("hoodMidSolenoid", hoodMidSolenoid);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // Slavery of the motors
    shooterMotor2->Follow(*shooterMotor1);
    shooterMotor3->Follow(*shooterMotor1);
    shooterMotor4->Follow(*shooterMotor1);
    // setting PID values of master
    //shooterMotor1->Config_kP(0,shooter_P);
    //shooterMotor1->Config_kI(0,shooter_I);
    //shooterMotor1->Config_kD(0,shooter_D);




}

void Shooter::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void Shooter::Periodic() {
    // Put code here to be run every loop

}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


// Put methods for controlling this subsystem
// here. Call these from Commands.

void Shooter::SetShooterSpeed(double speed) {
    //shooterMotor1->Set(ControlMode::PercentOutput,speed);
    shooterMotor1->Set(speed);
}

void Shooter::hoodPositionIn(){
    hoodSolenoid->Set(true);
}
void Shooter::hoodPositionOut(){
    hoodSolenoid->Set(false);
}
void Shooter::hoodMidPositionIn(){
    hoodMidSolenoid->Set(true);
}
void Shooter::hoodMidPositionOut(){
    hoodMidSolenoid->Set(false);
}

bool Shooter::hoodLow(){
    hoodPositionIn();
    hoodMidPositionIn();
    hoodState = low;
    return true;
}

bool Shooter::hoodMedium(){
    switch(hoodState){
        case low:
            switch(hoodCounter){
                case 0:
                    hoodMidPositionIn();
                    break;
                case 50:
                    hoodPositionOut();
                    hoodCounter = 0;
                    hoodState = medium;
                    return true;
            }
            hoodCounter++;
            break;
        case medium:
            return true;
        case high:
            switch(hoodCounter){
                case 0:
                    hoodPositionIn();
                    break;
                case 50:
                    hoodMidPositionIn();
                    break;
                case 100:
                    hoodPositionOut();
                    hoodCounter = 0;
                    hoodState = medium;
                    return true;
            }
            hoodCounter++;
            break;
    }
    return false;
}

bool Shooter::hoodHigh(){
    switch(hoodState){
        case low:
            hoodPositionOut();
            hoodState = high;
            return true;
        case medium:
            switch(hoodCounter){
                case 0:
                    hoodPositionIn();
                    break;
                case 50:
                    hoodMidPositionIn();
                    break;
                case 100:
                    hoodPositionOut();
                    hoodCounter = 0;
                    hoodState = high;
                    return true;
            }
            hoodCounter++;
            break;
        case high:
            return true;
    }
    return false;
}

void Shooter::stopShooter(){
    shooterMotor1->Disable();
}
